# Site settings
title: Agri-Inno
description: Agri-Innovation Workshop 2016

# Build settings
baseurl: "/"
permalink: /:categories/:title
markdown: kramdown

# Custom variables
version: "1.3"
timezone: Asia/Kuala_Lumpur

include:
  - _pages
  - assets

# Compression
compress_html:
  clippings: all
sass:
  style: compressed
